apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y06ilev2j-nodejs 
  janus-idp.io/tekton: y06ilev2j-nodejs
  backstage.io/kubernetes-id: y06ilev2j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y06ilev2j-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml